import { constants } from 'emberquest/services/constants';

export default {

  player: {
    startX: 7,
    startY: 3
  },

  mapUrl: '/images/maps/arena.png',

  chests: [
    // {id: 1, x: 10, y: 3, gccode: 'GC002', gold: 20, specialActions: []}
  ],

  spawnLocations : {
    players: [{x: 5, y: 3}], // tiles where the player may spawn
    transports: {
      spawnInterval: 3000,
      limit: 1,
      locations: []
    },
    agents: {
      spawnInterval: 3000,
      limit: 1,
      locations: [
        {id: 1, x: 6, y: 5, pool: [ 'dog' ], override: {levelRange: 2, health: 11, maxHealth: 11}, patrol: { method: 'wander', timeout: 4000, pursuitSpeed: 2000, aggressionSpeedTimeout: 1500 }}

      ]
    }
  },

  signs: [
    {
      id: 1, x: 5, y: 3,
      texture: 'signpost',
      textureSize: { width: 72, height: 72},
      scale: 0.7,
      signMessageId: 'msg1'  // key to use to display message on sign
    }
  ],


  sceneTiles: [
    [
      {'x': 0, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 5, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 11, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 5, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds^Edb', 'special': 0 },
      {'x': 7, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 11, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 5, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 11, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 5, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds^Edb', 'special': 0 },
      {'x': 11, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds^Edb', 'special': 0 },
      {'x': 5, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 11, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 5, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 11, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 5, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 11, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 5, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 11, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds^Edb', 'special': 0 },
      {'x': 5, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 11, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 5, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds^Edb', 'special': 0 },
      {'x': 11, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 5, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 11, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 1, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 2, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 3, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 4, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 5, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 6, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 7, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 8, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 9, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 10, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 11, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 12, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
      {'x': 13, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds', 'special': 0 },
    ],
  ]
}
