
export default {

  player: {
    startX: 7,
    startY: 3
  },

  mapUrl: '/images/maps/intro2.png',

  chests: [
    {id: 1, x: 10, y: 3, gccode: 'GC002', gold: 20, specialActions: []}
  ],

  spawnLocations : {
    players: [{x: 5, y: 7}], // tiles where the player may spawn
    transports: {
      spawnInterval: 3000,
      limit: 1,
      locations: []
    },
    agents: {
      spawnInterval: 3000,
      limit: 5,
      locations: []
    }
  },

  sceneTiles: [
    [
      {'row': 0, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 0, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 0, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 0, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 0, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 0, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 1, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 1, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 1, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 1, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 1, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 2, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 10, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 2, 'col': 11, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 2, 'col': 12, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 2, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 2, 'col': 14, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 2, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 2, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 3, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 8, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 3, 'col': 9, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 3, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 3, 'col': 11, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 3, 'col': 12, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 3, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 3, 'col': 14, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 3, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 3, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 4, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 6, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 4, 'col': 7, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Md^Xm'},
      {'row': 4, 'col': 8, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 4, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 4, 'col': 10, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 4, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 4, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 4, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 4, 'col': 14, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 4, 'col': 15, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 4, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 4, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 5, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 5, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 5, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 5, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 5, 'col': 4, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 5, 'col': 5, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 5, 'col': 6, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 5, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 5, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 5, 'col': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 5, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 5, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs'},
      {'row': 5, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 5, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 5, 'col': 14, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fmf'},
      {'row': 5, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 5, 'col': 16, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 5, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 5, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 5, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 5, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 5, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 6, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 6, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 6, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 6, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 6, 'col': 4, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 6, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 6, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 6, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 6, 'col': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 6, 'col': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 6, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 6, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 6, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 6, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 6, 'col': 14, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fmf'},
      {'row': 6, 'col': 15, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fmf'},
      {'row': 6, 'col': 16, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 6, 'col': 17, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 6, 'col': 18, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 6, 'col': 19, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 6, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 6, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 7, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 7, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 7, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 7, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 7, 'col': 4, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 7, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 7, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 7, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 7, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gd'},
      {'row': 7, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 7, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs^Fds'},
      {'row': 7, 'col': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 7, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll'},
      {'row': 7, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 7, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 7, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 7, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 7, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 7, 'col': 18, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 7, 'col': 19, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 7, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 7, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 8, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 8, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 8, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 8, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 8, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 8, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 8, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 8, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 8, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 8, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 8, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 8, 'col': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 8, 'col': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 8, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 8, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 8, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 8, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 8, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 8, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 8, 'col': 19, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 8, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 8, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 9, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 9, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 9, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 9, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 9, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 9, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 9, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 9, 'col': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 9, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg^Efm'},
      {'row': 9, 'col': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 9, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs^Fds'},
      {'row': 9, 'col': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 9, 'col': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 9, 'col': 13, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 9, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 9, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 9, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 9, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hhd'},
      {'row': 9, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 9, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 9, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 9, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 10, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 10, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 10, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 10, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 10, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 10, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 10, 'col': 6, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 10, 'col': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs^Fds'},
      {'row': 10, 'col': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 10, 'col': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 10, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs^Fds'},
      {'row': 10, 'col': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 10, 'col': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 10, 'col': 13, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 10, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 10, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 10, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 10, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 10, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 10, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 10, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 10, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 11, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 11, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 11, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 11, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 11, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 11, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 11, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gd'},
      {'row': 11, 'col': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs^Fds'},
      {'row': 11, 'col': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs^Fds'},
      {'row': 11, 'col': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 11, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 11, 'col': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs^Fds'},
      {'row': 11, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 11, 'col': 13, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fmf'},
      {'row': 11, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 11, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 11, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg^Efm'},
      {'row': 11, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 11, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 11, 'col': 19, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 11, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 11, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 12, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 12, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 12, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 12, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 12, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 12, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 12, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 12, 'col': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 12, 'col': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 12, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb^Es'},
      {'row': 12, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 12, 'col': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 12, 'col': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 12, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 12, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Re'},
      {'row': 12, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 12, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 12, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 12, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 12, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 12, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 12, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 13, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 13, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 13, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 13, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 13, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 13, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg^Efm'},
      {'row': 13, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 13, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 13, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 13, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 13, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 13, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 13, 'col': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 13, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Re'},
      {'row': 13, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 13, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 13, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 13, 'col': 17, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fmf'},
      {'row': 13, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 13, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 13, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 13, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 14, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 14, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 14, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 14, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 14, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 14, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 14, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb^Em'},
      {'row': 14, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg^Em'},
      {'row': 14, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs'},
      {'row': 14, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 14, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs^Fds'},
      {'row': 14, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 14, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb^Em'},
      {'row': 14, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 14, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs'},
      {'row': 14, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 14, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 14, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg^Efm'},
      {'row': 14, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 14, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 14, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 14, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 15, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 15, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 15, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 15, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 15, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 15, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 15, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll'},
      {'row': 15, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 15, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 15, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg^Efm'},
      {'row': 15, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 15, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 15, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Re'},
      {'row': 15, 'col': 13, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 15, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 15, 'col': 15, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 15, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 15, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 15, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hhd'},
      {'row': 15, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 15, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 15, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 16, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 16, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 16, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 16, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 16, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 16, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 16, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hhd'},
      {'row': 16, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 16, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 16, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 16, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 16, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 16, 'col': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 16, 'col': 13, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 16, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Re'},
      {'row': 16, 'col': 15, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 16, 'col': 16, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 16, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 16, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 16, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 16, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 16, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 17, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 17, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 17, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Ms^Xm'},
      {'row': 17, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 17, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 17, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 17, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 17, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 17, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 17, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 17, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Re'},
      {'row': 17, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 17, 'col': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 17, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gs'},
      {'row': 17, 'col': 14, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gll^Fp'},
      {'row': 17, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 17, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gd'},
      {'row': 17, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 17, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 17, 'col': 19, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 17, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 17, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
    [
      {'row': 18, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
      {'row': 18, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 18, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 18, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 18, 'col': 4, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 18, 'col': 5, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 18, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 18, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 18, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Hh'},
      {'row': 18, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 18, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Rb'},
      {'row': 18, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 18, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 18, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 18, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 18, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 18, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Gg'},
      {'row': 18, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 18, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Mm'},
      {'row': 18, 'col': 19, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 18, 'col': 20, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Mm^Xm'},
      {'row': 18, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xv'},
    ],
  ]
}
