export default {

  player: {
    startX: 7,
    startY: 3
  },

  mapUrl: '/images/maps/testhex1.png',

  sceneTiles: [
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 1, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 1, 'travelFlags': 2},{'sightFlags': 1, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 2},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
    [{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},{'sightFlags': 0, 'travelFlags': 1},],
  ]
}
