
export default {

  player: {
    startX: 23,
    startY: 14
  },

  mapUrl: '/images/maps/cave1.png',

  // cave2_fast ends at x:18, y:17

  spawnLocations : {
    players: [{x: 23, y: 14}], // tiles where the player may spawn
    transports: {
      spawnInterval: 3000,
      limit: 1,
      locations: []
    },
    chests: { spawnInterval: 3000, limit: 1, locations: [{id: 1, x: 24, y: 17}]},
    agents: { spawnInterval: 3000, limit: 5,
      locations: [
        {
          // id: 2, x: 20, y: 11,
          id: 2, x: 21, y: 20,
          texture: 'vue',
          textureSize: { width: 42, height: 42},
          scale: 0.15,
          // speed: 2000,
          speed: 200,
          sightRange: 3,   // this is sight/movement Range
          movingPoints: 3,   // this is sight/movement Range
          visiblePoints: 8,   // this is sight/movement Range
          health: 100,
          maxHealth: 200,
          power: 15,
          healingPower: 10,
          // power: 20,
          // maxPower: 200,
          flagAttributes: {
            sightFlags: 0,
            travelFlags: 2
          },
          patrol: {
            // timeout: 200,
            timeout: 2000,
            pursuitSpeed: 1500,
            aggressionSpeedTimeout: 1000,
            // aggressionTimeout: 1000,  // delay time in between aggression turns
            method: 'random',
            tiles: [
              // {x: 20, y: 11}, {x: 19, y: 14}
              {x: 21, y: 20}, {x: 23, y: 18}
            ]
          },
          weapons: [  // this should be an id from the inventory items
            {
              minDistanceForHit: 10,
              type: 'bullet',
              damage: 1,
              speed: 8, // projectile speed
              poweruse: 2,
              accuracy: 0.05, // percentage 0 (always accurate) - 1 (shoot any direction)
              fireDelay: 500,
              reloadDelay: 1000  // lower is faster
            }
          ]
        }

      ]
    }
  },


  sceneTiles: [
    [
      {'row': 0, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 0, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 1, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 1, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 1, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 2, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 2, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 2, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 2, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 2, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 2, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc^Efs'},
      {'row': 2, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 2, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 3, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 3, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 3, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 3, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 3, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb^Efs'},
      {'row': 3, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 3, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb^Ecf'},
      {'row': 3, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb^Efs'},
      {'row': 3, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 3, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 3, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 3, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 4, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 4, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 4, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Qxu^Bs/'},
      {'row': 4, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 4, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 4, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 4, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 4, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 4, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Kud'},
      {'row': 4, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 4, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 5, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 5, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 5, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 5, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 5, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 5, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 5, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 5, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 5, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 5, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 5, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 6, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 6, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 6, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 6, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur^Efs'},
      {'row': 6, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur^Efs'},
      {'row': 6, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur^Efs'},
      {'row': 6, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 6, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 6, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xuc'},
      {'row': 6, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 6, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 7, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Urb'},
      {'row': 7, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 7, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 7, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 7, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 7, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur^Em'},
      {'row': 7, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 7, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 8, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xue'},
      {'row': 8, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 8, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 8, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xue'},
      {'row': 8, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 8, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 9, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 9, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 9, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 9, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xue'},
      {'row': 9, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 9, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 10, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 10, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 10, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 10, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uue'},
      {'row': 10, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 10, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 10, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uue'},
      {'row': 10, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 10, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 10, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 10, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 11, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur^Em'},
      {'row': 11, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 11, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 11, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 11, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 11, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu^Em'},
      {'row': 11, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 11, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 12, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 12, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 12, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 12, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 12, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 12, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu^Es'},
      {'row': 12, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu^Em'},
      {'row': 12, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uue'},
      {'row': 12, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uue^Edb'},
      {'row': 12, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu^Es'},
      {'row': 12, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 12, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 12, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 12, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 13, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 13, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 13, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 13, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 13, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 13, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur^Es'},
      {'row': 13, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 13, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 13, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 13, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 13, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 13, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 13, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 13, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 13, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 13, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uue'},
      {'row': 13, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 13, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 13, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 13, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 13, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 13, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uue'},
      {'row': 13, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Qxu^Bh\\'},
      {'row': 13, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 13, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 13, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 13, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 13, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 14, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 14, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 14, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 14, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 14, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Qxu^Bs\\'},
      {'row': 14, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 14, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 14, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 14, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 14, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 14, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 14, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 14, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 14, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 14, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 14, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 14, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 14, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 14, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 14, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 14, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uue'},
      {'row': 14, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu'},
      {'row': 14, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 14, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Qxu^Bh\\'},
      {'row': 14, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': {value:2,map:'landsea',x:1,y:5}, 'wesnoth': 'Qxu^Bh\\'},
      {'row': 14, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 14, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 14, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 15, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 15, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 15, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 15, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Qxu^Bs\\'},
      {'row': 15, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 15, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 15, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 15, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 15, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 15, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Ql'},
      {'row': 15, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 15, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 16, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 16, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 16, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 16, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 16, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 16, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Qxu^Bs\\'},
      {'row': 16, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 16, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Qxu^Bs/'},
      {'row': 16, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur^Edb'},
      {'row': 16, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Qxu^Bs\\'},
      {'row': 16, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 16, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 16, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 16, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 16, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 17, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 17, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 17, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 17, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 17, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 17, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 17, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 17, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 17, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 17, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 17, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 17, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 17, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 17, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 17, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur^Es'},
      {'row': 17, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 17, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur^Edt'},
      {'row': 17, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uh'},
      {'row': 17, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 17, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur^Es'},
      {'row': 17, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 17, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 17, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 17, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uu^Vu'},
      {'row': 17, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 17, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 17, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 17, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 18, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 18, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 18, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 18, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 18, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 18, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 18, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 18, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 18, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 18, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 18, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 18, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Uh'},
      {'row': 18, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 18, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 18, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 18, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 19, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 19, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 19, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 19, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 19, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 19, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 19, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 19, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 19, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 19, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 19, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 20, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qlf'},
      {'row': 20, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 4, 'special': 0, 'wesnoth': 'Qxe'},
      {'row': 20, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 20, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'special': 0, 'wesnoth': 'Ur'},
      {'row': 20, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 20, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
    [
      {'row': 21, 'col': 0, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 1, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 2, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 3, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 4, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 5, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 6, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 7, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 8, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 9, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 10, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 11, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 19, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 20, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 21, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 22, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 23, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 24, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 25, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 26, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
      {'row': 21, 'col': 27, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'special': 0, 'wesnoth': 'Xu'},
    ],
  ]
}
