import { constants } from './constants';

export default {

  player: {
    startX: 7,
    startY: 3
  },

  mapUrl: '/images/maps/intro2.png',

  chests: [
    {id: 1, x: 10, y: 3, gccode: 'GC8QB0H', gold: 20, specialActions: []}
  ],

  uniques: {
    agents: [
      {uniqueId: 1, x: 13, y: 2, agentKey: 'young-ogre', override: {aggressionScale: 0}, patrol: { method: 'random', tiles: [{x: 13, y: 4}, {x: 13, y: 2}] } }
    ]
  },

  spawnLocations : {
    players: [{x: 5, y: 7}], // tiles where the player may spawn
    transports: {
      spawnInterval: 3000,
      limit: 1,
      locations: []
    },
    agents: {
      spawnInterval: 3000,
      limit: 5,
      locations: []
    }
  },

  sceneTiles: [
    [
      {'x': 0, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs', 'special': 0 },
      {'x': 1, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 2, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 3, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 4, 'y': 0, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 5, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 6, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt', 'special': {value:constants.FLAGS.SPECIAL.PORTAL.value,map:'intro3',x:4,y:13} },
      {'x': 7, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': {value:constants.FLAGS.SPECIAL.PORTAL.value,map:'intro3',x:4,y:13} },
      {'x': 8, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': {value:constants.FLAGS.SPECIAL.PORTAL.value,map:'intro3',x:4,y:13} },
      {'x': 9, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 10, 'y': 0, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 11, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 12, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 13, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': {value:constants.FLAGS.SPECIAL.PORTAL.value,map:'intro3',x:14,y:13}},
      {'x': 14, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 15, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 16, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 17, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 18, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': {value:constants.FLAGS.SPECIAL.PORTAL.value,map:'intro3',x:38,y:13} },
      {'x': 19, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': {value:constants.FLAGS.SPECIAL.PORTAL.value,map:'intro3',x:38,y:13} },
      {'x': 20, 'y': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 21, 'y': 0, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fms', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 1, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 2, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 3, 'y': 1, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 4, 'y': 1, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 5, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 6, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 7, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 8, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 9, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 10, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 11, 'y': 1, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 12, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg^Em', 'special': 0 },
      {'x': 13, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 14, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 15, 'y': 1, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fms', 'special': 0 },
      {'x': 16, 'y': 1, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 17, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 18, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 19, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 20, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 21, 'y': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 1, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 2, 'y': 2, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fms', 'special': 0 },
      {'x': 3, 'y': 2, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 4, 'y': 2, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 5, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 6, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 7, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 8, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 9, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Re^Esd', 'special': 0 },
      {'x': 10, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 11, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 12, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 13, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 14, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 15, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 16, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt', 'special': 0 },
      {'x': 17, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt', 'special': 0 },
      {'x': 18, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 19, 'y': 2, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fms', 'special': 0 },
      {'x': 20, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 21, 'y': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 1, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 2, 'y': 3, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 3, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 4, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 5, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 6, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 7, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 8, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg', 'special': 0 },
      {'x': 9, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 10, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rd', 'special': 0 },
      {'x': 11, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 12, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt', 'special': 0 },
      {'x': 13, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 7, 'w': 'Ww^Bw|', 'special': 1 },
      {'x': 14, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 15, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 16, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 17, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 18, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 19, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 20, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 21, 'y': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 1, 'y': 4, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fdf', 'special': 0 },
      {'x': 2, 'y': 4, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 3, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 4, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 5, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 6, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 7, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 8, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 9, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 10, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 11, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 12, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 13, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 14, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 15, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 16, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd^Em', 'special': 0 },
      {'x': 17, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 18, 'y': 4, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fdf', 'special': 0 },
      {'x': 19, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 20, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 21, 'y': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 1, 'y': 5, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fms', 'special': 0 },
      {'x': 2, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 3, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 4, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 5, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt', 'special': 0 },
      {'x': 6, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 7, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 8, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 9, 'y': 5, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 10, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 11, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs', 'special': 0 },
      {'x': 12, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 13, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 14, 'y': 5, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmf', 'special': 0 },
      {'x': 15, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 16, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 17, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 18, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 19, 'y': 5, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 20, 'y': 5, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fdf', 'special': 0 },
      {'x': 21, 'y': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg^Efm', 'special': 0 },
      {'x': 1, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 2, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs', 'special': 0 },
      {'x': 3, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 4, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 5, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 6, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg', 'special': 0 },
      {'x': 7, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rd', 'special': 0 },
      {'x': 8, 'y': 6, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 9, 'y': 6, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 10, 'y': 6, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 11, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 12, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 13, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 14, 'y': 6, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmf', 'special': 0 },
      {'x': 15, 'y': 6, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmf', 'special': 0 },
      {'x': 16, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 17, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 18, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 19, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 20, 'y': 6, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 21, 'y': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 1, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 2, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 3, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 4, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 5, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 6, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 7, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 8, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 9, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 10, 'y': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fds', 'special': 0 },
      {'x': 11, 'y': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 12, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 13, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 14, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 15, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 16, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 17, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 18, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 19, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg^Efm', 'special': 0 },
      {'x': 20, 'y': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 21, 'y': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 1, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 2, 'y': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 3, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 4, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 5, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 6, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 7, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 8, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 9, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 10, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 11, 'y': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 12, 'y': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 13, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 14, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 15, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 16, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rd', 'special': 0 },
      {'x': 17, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 18, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 19, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg^Efm', 'special': 0 },
      {'x': 20, 'y': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 21, 'y': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fms', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg^Em', 'special': 0 },
      {'x': 1, 'y': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 2, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg', 'special': 0 },
      {'x': 3, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 4, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 5, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rd', 'special': 0 },
      {'x': 6, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 7, 'y': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 8, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg^Efm', 'special': 0 },
      {'x': 9, 'y': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 10, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 6, 'w': 'Ss', 'special': 0 },
      {'x': 11, 'y': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 12, 'y': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 13, 'y': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 14, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 15, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 16, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 17, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
      {'x': 18, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 19, 'y': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 20, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 21, 'y': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 1, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 2, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 3, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 4, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 5, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 6, 'y': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 7, 'y': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fds', 'special': 0 },
      {'x': 8, 'y': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 9, 'y': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 10, 'y': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fds', 'special': 0 },
      {'x': 11, 'y': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 12, 'y': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 13, 'y': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 14, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 15, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 16, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 17, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 18, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 19, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 20, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 21, 'y': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 1, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 2, 'y': 11, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm', 'special': 0 },
      {'x': 3, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 4, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 5, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 6, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 7, 'y': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fds', 'special': 0 },
      {'x': 8, 'y': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fds', 'special': 0 },
      {'x': 9, 'y': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 10, 'y': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 11, 'y': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fds', 'special': 0 },
      {'x': 12, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 13, 'y': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmf', 'special': 0 },
      {'x': 14, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 15, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 16, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg^Efm', 'special': 0 },
      {'x': 17, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 18, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 19, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 20, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rd', 'special': 0 },
      {'x': 21, 'y': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 12, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'w': 'Xv', 'special': 0 },
      {'x': 1, 'y': 12, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 2, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
      {'x': 3, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 4, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 5, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 6, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 7, 'y': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 8, 'y': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 9, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb^Es', 'special': 0 },
      {'x': 10, 'y': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 11, 'y': 12, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 12, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 13, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 14, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Re', 'special': 0 },
      {'x': 15, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 16, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 17, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 18, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 19, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 20, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 21, 'y': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 13, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'w': 'Xv', 'special': 0 },
      {'x': 1, 'y': 13, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 2, 'y': 13, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 3, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 4, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 5, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg^Efm', 'special': 0 },
      {'x': 6, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 7, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 8, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 9, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 6, 'w': 'Ss', 'special': 0 },
      {'x': 10, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 11, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 12, 'y': 13, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 13, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 7, 'w': 'Ww^Bw/', 'special': 1 },
      {'x': 14, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 15, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 16, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 17, 'y': 13, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmf', 'special': 0 },
      {'x': 18, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 19, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt', 'special': 0 },
      {'x': 20, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 21, 'y': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 14, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'w': 'Xv', 'special': 0 },
      {'x': 1, 'y': 14, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 2, 'y': 14, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 3, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 4, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 5, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 6, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb^Em', 'special': 0 },
      {'x': 7, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 8, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 9, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 10, 'y': 14, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fds', 'special': 0 },
      {'x': 11, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 12, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb^Em', 'special': 0 },
      {'x': 13, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 14, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs', 'special': 0 },
      {'x': 15, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 16, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 17, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 18, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 19, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 20, 'y': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
      {'x': 21, 'y': 14, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 15, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'w': 'Xv', 'special': 0 },
      {'x': 1, 'y': 15, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 2, 'y': 15, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 3, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 4, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 5, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 6, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 7, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 8, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 9, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg^Efm', 'special': 0 },
      {'x': 10, 'y': 15, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 11, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 12, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Re', 'special': 0 },
      {'x': 13, 'y': 15, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 14, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 15, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 16, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 17, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll', 'special': 0 },
      {'x': 18, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
      {'x': 19, 'y': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt', 'special': 0 },
      {'x': 20, 'y': 15, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm', 'special': 0 },
      {'x': 21, 'y': 15, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 16, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'w': 'Xv', 'special': 0 },
      {'x': 1, 'y': 16, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm', 'special': 0 },
      {'x': 2, 'y': 16, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm', 'special': 0 },
      {'x': 3, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
      {'x': 4, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 5, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 6, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
      {'x': 7, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 8, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 9, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 10, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 11, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': 0 },
      {'x': 12, 'y': 16, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 13, 'y': 16, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 14, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Re', 'special': 0 },
      {'x': 15, 'y': 16, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 16, 'y': 16, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 17, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 18, 'y': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 19, 'y': 16, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm', 'special': 0 },
      {'x': 20, 'y': 16, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm', 'special': 0 },
      {'x': 21, 'y': 16, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 17, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'w': 'Xv', 'special': 0 },
      {'x': 1, 'y': 17, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm', 'special': 0 },
      {'x': 2, 'y': 17, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm', 'special': 0 },
      {'x': 3, 'y': 17, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 4, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Mm', 'special': 0 },
      {'x': 5, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 6, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 7, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 8, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 9, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 10, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Re', 'special': 0 },
      {'x': 11, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 12, 'y': 17, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 13, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs', 'special': 0 },
      {'x': 14, 'y': 17, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 15, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 16, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd', 'special': 0 },
      {'x': 17, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh', 'special': 0 },
      {'x': 18, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
      {'x': 19, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
      {'x': 20, 'y': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Mm', 'special': 0 },
      {'x': 21, 'y': 17, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm', 'special': 0 },
    ],
    [
      {'x': 0, 'y': 18, 'sightCost': 7, 'sightFlags': 1, 'speedCost': 1, 'travelFlags': 8, 'w': 'Xv', 'special': 0 },
      {'x': 1, 'y': 18, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 2, 'y': 18, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 3, 'y': 18, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 4, 'y': 18, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mm^Xm', 'special': 0 },
      {'x': 5, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
      {'x': 6, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 7, 'y': 18, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp', 'special': 0 },
      {'x': 8, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww', 'special': 0 },
      {'x': 9, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 10, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb', 'special': {value:constants.FLAGS.SPECIAL.PORTAL.value,map:'intro',x:11,y:2} },
      {'x': 11, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 12, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 13, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 14, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 15, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 16, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg', 'special': 0 },
      {'x': 17, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd', 'special': 0 },
      {'x': 18, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Mm', 'special': 0 },
      {'x': 19, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Mm', 'special': 0 },
      {'x': 20, 'y': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Mm', 'special': 0 },
      {'x': 21, 'y': 18, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm', 'special': 0 },
    ],
  ]
}
