import { constants } from 'emberquest/services/constants';

export default {

  player: {
    startX: 5,
    startY: 7
  },
  // player: {
  //   startX: 6,
  //   startY: 15
  // },

  mapUrl: '/images/maps/landsea-min.png',

  spawnLocations : {
    players: [{x: 5, y: 7}], // tiles where the player may spawn
    // players: [{x: 6, y: 15}], // tiles where the player may spawn
    transports: {
      spawnInterval: 3000,
      limit: 1,
      locations: [
        {
          id: 1, x: 3, y: 17,
          texture: 'playership',
          textureSize: { width: 42, height: 42},
          scale: 0.4,
          speed: 200,
          sightRange: 3,   // this is sight/movement Range
          movingPoints: 3,   // this is sight/movement Range
          visiblePoints: 8,   // this is sight/movement Range
          health: 100,
          maxHealth: 200,
          healingPower: 10,
          power: 190,
          // maxPower: 200,
          flagAttributes: {
            sightFlags: 0,
            travelFlags: 1
          },
        }
      ]
    },
    chests: { spawnInterval: 3000, limit: 1, locations: []},
    // chests: { spawnInterval: 3000, limit: 1, locations: [{id: 1, x: 3, y: 11}, {id: 2, x: 5, y: 9}]},
    // monsters: { spawnInterval: 3000, limit: 1, locations: [{id: 1, x: 8, y: 8, health: 100, maxHealth: 200,scale: 0.75}]},
    agents: { spawnInterval: 3000, limit: 5,
      locations: [
        {
          id: 1, x: 10, y: 16,
          texture: 'galleon',
          textureSize: { width: 42, height: 42},
          scale: 0.1,
          speed: 200,
          sightRange: 3,   // this is sight/movement Range
          movingPoints: 3,   // this is sight/movement Range
          visiblePoints: 8,   // this is sight/movement Range
          health: 10,
          // maxHealth: 20,
          healingPower: 10,
          power: 190,
          // maxPower: 200,
          flagAttributes: {
            sightFlags: 0,
            travelFlags: 1
          },
          patrol: {
            timeout: 2000,
            // aggressionTimeout: 1000,  // delay time in between aggression turns
            method: 'random',
            tiles: [
              {x: 10, y: 16}, {x: 7, y: 14}, {x: 11, y: 15}
            ]
          }
        },
        // {
        //   id: 2, x: 7, y: 7,
        //   texture: 'vue',
        //   textureSize: { width: 42, height: 42},
        //   scale: 0.15,
        //   speed: 200,
        //   sightRange: 3,   // this is sight/movement Range
        //   movingPoints: 3,   // this is sight/movement Range
        //   visiblePoints: 8,   // this is sight/movement Range
        //   health: 100,
        //   maxHealth: 200,
        //   power: 20,
        //   maxPower: 200,
        //   flagAttributes: {
        //     sightFlags: 0,
        //     travelFlags: 2
        //   },
        //   patrol: {
        //     timeout: 2000,
        //     // aggressionTimeout: 1000,  // delay time in between aggression turns
        //     method: 'random',
        //     tiles: [
        //       {x: 2, y: 3}, {x: 6, y: 5}
        //     ]
        //   }
        // }

      ]
    }
  },

  sceneTiles: [
    [
      {'row': 0, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 4, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 5, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 6, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 7, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 8, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 9, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 10, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 11, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Ha'},
      {'row': 0, 'col': 13, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 14, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 0, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 0, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 0, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 0, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 0, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 0, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 0, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 0, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 0, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 0, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 0, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 0, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Re'},
      {'row': 0, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 0, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 0, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll'},
      {'row': 0, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd'},
      {'row': 0, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 0, 'col': 32, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 0, 'col': 33, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
    ],
    [
      {'row': 1, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 1, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 1, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 1, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 1, 'col': 4, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 1, 'col': 5, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 1, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Ha'},
      {'row': 1, 'col': 7, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 1, 'col': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 1, 'col': 9, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 1, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 1, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Ha'},
      {'row': 1, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Ha'},
      {'row': 1, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Ha'},
      {'row': 1, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Ha'},
      {'row': 1, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Re'},
      {'row': 1, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
      {'row': 1, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 1, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 1, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd'},
      {'row': 1, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
      {'row': 1, 'col': 32, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 1, 'col': 33, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
    ],
    [
      {'row': 2, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 2, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 2, 'col': 2, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fpa'},
      {'row': 2, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 2, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 2, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa^Es'},
      {'row': 2, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 2, 'col': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 2, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 2, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 2, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 2, 'col': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fpa'},
      {'row': 2, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa^Es'},
      {'row': 2, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 2, 'col': 14, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fpa'},
      {'row': 2, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 2, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 2, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
      {'row': 2, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 2, 'col': 31, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 2, 'col': 32, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 2, 'col': 33, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
    ],
    [
      {'row': 3, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 3, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 4, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 3, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 3, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fpa'},
      {'row': 3, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 3, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 3, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 3, 'col': 30, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fdw'},
      {'row': 3, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 3, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs^Vl'},
      {'row': 3, 'col': 33, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
    ],
    [
      {'row': 4, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 4, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 4, 'col': 2, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 4, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Ms'},
      {'row': 4, 'col': 4, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 4, 'col': 5, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 4, 'col': 6, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 4, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 4, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 4, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 4, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 4, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 4, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 4, 'col': 13, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 4, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 4, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 4, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 4, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
      {'row': 4, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd'},
      {'row': 4, 'col': 29, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fdw'},
      {'row': 4, 'col': 30, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fdw'},
      {'row': 4, 'col': 31, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fdw'},
      {'row': 4, 'col': 32, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fdw'},
      {'row': 4, 'col': 33, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
    ],
    [
      {'row': 5, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 5, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 5, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Kud','special':{value:constants.FLAGS.SPECIAL.PORTAL.value,map:'cave1',x:23,y:14}},
      {'row': 5, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 5, 'col': 4, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 5, 'col': 5, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 5, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 5, 'col': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fpa'},
      {'row': 5, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 5, 'col': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 5, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 5, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 5, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 5, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww'},
      {'row': 5, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 5, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd'},
      {'row': 5, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 5, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 5, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 5, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll'},
      {'row': 5, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd'},
      {'row': 5, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb'},
      {'row': 5, 'col': 33, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
    ],
    [
      {'row': 6, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 6, 'col': 1, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 6, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 6, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 6, 'col': 4, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 6, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 6, 'col': 6, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 6, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 6, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa^Es'},
      {'row': 6, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 6, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 6, 'col': 11, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmf'},
      {'row': 6, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 6, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 6, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 6, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 6, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 6, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 6, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wog'},
      {'row': 6, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wog'},
      {'row': 6, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 6, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww'},
      {'row': 6, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww'},
      {'row': 6, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 6, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 6, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 6, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Re'},
      {'row': 6, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 6, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb'},
      {'row': 6, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 6, 'col': 30, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 6, 'col': 31, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 6, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb'},
      {'row': 6, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd'},
    ],
    [
      {'row': 7, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 7, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 7, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 7, 'col': 3, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 7, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 7, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 7, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 7, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 7, 'col': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmf'},
      {'row': 7, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 7, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmw'},
      {'row': 7, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 7, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 7, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 7, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 7, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 7, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 7, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww'},
      {'row': 7, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww'},
      {'row': 7, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 7, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 7, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 7, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww'},
      {'row': 7, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 7, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 7, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 7, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
      {'row': 7, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 7, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Re'},
      {'row': 7, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 7, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 7, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 7, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
      {'row': 7, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
    ],
    [
      {'row': 8, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 8, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 8, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 8, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 8, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Mm'},
      {'row': 8, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 8, 'col': 6, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 8, 'col': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmf'},
      {'row': 8, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 8, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 8, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
      {'row': 8, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd'},
      {'row': 8, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 8, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 8, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 8, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 8, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 8, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 8, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww'},
      {'row': 8, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 8, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 8, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wog'},
      {'row': 8, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 8, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 8, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 8, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 6, 'w': 'Sm'},
      {'row': 8, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 6, 'w': 'Sm'},
      {'row': 8, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 8, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 8, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll'},
      {'row': 8, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 8, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb'},
      {'row': 8, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 8, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
    ],
    [
      {'row': 9, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 9, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 9, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Mm'},
      {'row': 9, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 9, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Mm'},
      {'row': 9, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb'},
      {'row': 9, 'col': 6, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 9, 'col': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 9, 'col': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 9, 'col': 9, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 9, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd^Es'},
      {'row': 9, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb^Em'},
      {'row': 9, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 9, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 9, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 9, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 9, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 9, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 9, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 9, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 9, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 9, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 9, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 9, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 9, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 9, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 9, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 9, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs^Es'},
      {'row': 9, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs^Efm'},
      {'row': 9, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 9, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 9, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Re'},
      {'row': 9, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 9, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
    ],
    [
      {'row': 10, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 10, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 10, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 10, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Mm'},
      {'row': 10, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh'},
      {'row': 10, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 10, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd'},
      {'row': 10, 'col': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 10, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 10, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 10, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 10, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 10, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 10, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg^Em'},
      {'row': 10, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 10, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 10, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs^Efm'},
      {'row': 10, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 10, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs^Es'},
      {'row': 10, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 10, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg'},
      {'row': 10, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
      {'row': 10, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg'},
      {'row': 10, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
    ],
    [
      {'row': 11, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 11, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 11, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh'},
      {'row': 11, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 11, 'col': 4, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 11, 'col': 5, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmf'},
      {'row': 11, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 11, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 11, 'col': 8, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmw'},
      {'row': 11, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 11, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 11, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 11, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 11, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll'},
      {'row': 11, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 11, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 11, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 11, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 11, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 11, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wog'},
      {'row': 11, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wog'},
      {'row': 11, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wog'},
      {'row': 11, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wog'},
      {'row': 11, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 11, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 11, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 11, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb'},
      {'row': 11, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs^Es'},
      {'row': 11, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 11, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd^Efm'},
      {'row': 11, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg'},
      {'row': 11, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 2, 'w': 'Wo^Bw|r', 'special': 1},
      {'row': 11, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg'},
      {'row': 11, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
    ],
    [
      {'row': 12, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 12, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hh'},
      {'row': 12, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
      {'row': 12, 'col': 3, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 12, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd'},
      {'row': 12, 'col': 5, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmw'},
      {'row': 12, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 12, 'col': 7, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmw'},
      {'row': 12, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs^Efm'},
      {'row': 12, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs^Efm'},
      {'row': 12, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 12, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll'},
      {'row': 12, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 12, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww'},
      {'row': 12, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 12, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb'},
      {'row': 12, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 12, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 12, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg'},
      {'row': 12, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg'},
      {'row': 12, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gll'},
    ],
    [
      {'row': 13, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Md^Xm'},
      {'row': 13, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd'},
      {'row': 13, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd'},
      {'row': 13, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd'},
      {'row': 13, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 13, 'col': 5, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fmw'},
      {'row': 13, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 13, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 13, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 13, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 13, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 13, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 13, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 13, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wog'},
      {'row': 13, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 13, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg'},
      {'row': 13, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
    ],
    [
      {'row': 14, 'col': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd'},
      {'row': 14, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.7, 'travelFlags': 6, 'w': 'Hhd'},
      {'row': 14, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 14, 'col': 3, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gll^Fp'},
      {'row': 14, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gg'},
      {'row': 14, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 14, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs^Efm'},
      {'row': 14, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 14, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 14, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 14, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 14, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wog'},
      {'row': 14, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 14, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Ww'},
      {'row': 14, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg'},
      {'row': 14, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rb'},
      {'row': 14, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gd'},
    ],
    [
      {'row': 15, 'col': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 15, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 15, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 15, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 15, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 15, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 15, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 15, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 6, 'w': 'Gs'},
      {'row': 15, 'col': 10, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Fms'},
      {'row': 15, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 15, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 15, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 15, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 15, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwg'},
    ],
    [
      {'row': 16, 'col': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 16, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 16, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 16, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwf'},
      {'row': 16, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 2, 'w': 'Wwt^Bw/', 'special': 1},
      {'row': 16, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rr'},
      {'row': 16, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 16, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 16, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 16, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 16, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 16, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 16, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 16, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 16, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
    ],
    [
      {'row': 17, 'col': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 17, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 17, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 17, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 17, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 17, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 17, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwf'},
      {'row': 17, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 17, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Dd'},
      {'row': 17, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Dd'},
      {'row': 17, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds^Es'},
      {'row': 17, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 17, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 17, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 17, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 17, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 17, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 17, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
    ],
    [
      {'row': 18, 'col': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwf'},
      {'row': 18, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwf'},
      {'row': 18, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 18, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 18, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 18, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 18, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Dd^Es'},
      {'row': 18, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Md'},
      {'row': 18, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Dd^Vdr'},
      {'row': 18, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Dd'},
      {'row': 18, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Dd'},
      {'row': 18, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 18, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 18, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 18, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 18, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 18, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 18, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 18, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 18, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 18, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 18, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
    ],
    [
      {'row': 19, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mdd^Xm'},
      {'row': 19, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwf'},
      {'row': 19, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mdd^Xm'},
      {'row': 19, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwf'},
      {'row': 19, 'col': 4, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Ft'},
      {'row': 19, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 19, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 19, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 19, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 19, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 19, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Md'},
      {'row': 19, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Mv'},
      {'row': 19, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Dd'},
      {'row': 19, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Dd'},
      {'row': 19, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 19, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 2, 'w': 'Wo^Bw\\r', 'special': 1},
      {'row': 19, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 19, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 19, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 19, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 19, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 19, 'col': 32, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 19, 'col': 33, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
    ],
    [
      {'row': 20, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mdd^Xm'},
      {'row': 20, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mdd^Xm'},
      {'row': 20, 'col': 2, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mdd^Xm'},
      {'row': 20, 'col': 3, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Ft'},
      {'row': 20, 'col': 4, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gd^Fetd'},
      {'row': 20, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 20, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rd'},
      {'row': 20, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 20, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 20, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 20, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 20, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 20, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Dd'},
      {'row': 20, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 20, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 20, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 20, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 20, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 20, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 2, 'w': 'Wwt^Bw\\', 'special': 1},
      {'row': 20, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 20, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 20, 'col': 32, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 20, 'col': 33, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
    ],
    [
      {'row': 21, 'col': 0, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mdd^Xm'},
      {'row': 21, 'col': 1, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Mdd^Xm'},
      {'row': 21, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rd^Es'},
      {'row': 21, 'col': 3, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.65, 'travelFlags': 6, 'w': 'Gs^Ft'},
      {'row': 21, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 21, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 21, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 21, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 21, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 21, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 21, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 21, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 21, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 21, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 21, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 21, 'col': 32, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 21, 'col': 33, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
    ],
    [
      {'row': 22, 'col': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwrt'},
      {'row': 22, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1.2, 'travelFlags': 6, 'w': 'Rd'},
      {'row': 22, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwrt'},
      {'row': 22, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ds'},
      {'row': 22, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 22, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 22, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 22, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 22, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 22, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 22, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 22, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 22, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 22, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 22, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 22, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 22, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa^Es'},
      {'row': 22, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 22, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Ms'},
      {'row': 22, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Ms'},
      {'row': 22, 'col': 32, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 22, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
    ],
    [
      {'row': 23, 'col': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwrt'},
      {'row': 23, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwrt'},
      {'row': 23, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 23, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 23, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wo'},
      {'row': 23, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 23, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 23, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 23, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 23, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 23, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 23, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 23, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 23, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 23, 'col': 24, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 23, 'col': 25, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 23, 'col': 26, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fda'},
      {'row': 23, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 4, 'w': 'Ms'},
      {'row': 23, 'col': 28, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 23, 'col': 29, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 23, 'col': 30, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 23, 'col': 31, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 23, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa^Vaa'},
      {'row': 23, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
    ],
    [
      {'row': 24, 'col': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwrt'},
      {'row': 24, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wot'},
      {'row': 24, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 24, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 24, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 24, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 24, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 24, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 24, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 24, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 24, 'col': 21, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 24, 'col': 22, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fda'},
      {'row': 24, 'col': 23, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 24, 'col': 24, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 24, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 24, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 24, 'col': 27, 'sightCost': 7, 'sightFlags': 0, 'speedCost': 0.3, 'travelFlags': 8, 'w': 'Ms^Xm'},
      {'row': 24, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 24, 'col': 29, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 24, 'col': 30, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 24, 'col': 31, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fma'},
      {'row': 24, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 24, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
    ],
    [
      {'row': 25, 'col': 0, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 1, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 2, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 3, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 4, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 5, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 6, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 7, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 8, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 9, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 10, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 11, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 12, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 1, 'travelFlags': 5, 'w': 'Wwt'},
      {'row': 25, 'col': 13, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 25, 'col': 14, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 25, 'col': 15, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 25, 'col': 16, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 25, 'col': 17, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 25, 'col': 18, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 25, 'col': 19, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Ai'},
      {'row': 25, 'col': 20, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 25, 'col': 21, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fpa'},
      {'row': 25, 'col': 22, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 25, 'col': 23, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fpa'},
      {'row': 25, 'col': 24, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fpa'},
      {'row': 25, 'col': 25, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 25, 'col': 26, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 25, 'col': 27, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 25, 'col': 28, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 25, 'col': 29, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fpa'},
      {'row': 25, 'col': 30, 'sightCost': 5, 'sightFlags': 0, 'speedCost': 0.55, 'travelFlags': 6, 'w': 'Aa^Fpa'},
      {'row': 25, 'col': 31, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 25, 'col': 32, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
      {'row': 25, 'col': 33, 'sightCost': 1, 'sightFlags': 0, 'speedCost': 0.9, 'travelFlags': 6, 'w': 'Aa'},
    ],
  ]
}
